// IANA timezone -> country name, used only as the *fallback* signal in
// js/app.js's geo-based preset defaults when the Geolocation API is denied,
// unsupported, or times out (see detectUserLocation()). Deliberately not
// city-level — most zones are shared by many candidate cities (e.g.
// America/Los_Angeles covers LA, SF, and Portland), so this only ever
// narrows a guess down to a country; city-level matching happens from the
// Geolocation API's actual coordinates against films/index.json's and
// labs/index.json's own lat/lon fields instead.
//
// This table is intentionally comprehensive — covering every populated
// zone in the IANA tz database, not just the countries films/labs presets
// currently have — so it never needs a maintenance pass when a new
// country's preset file ships. Country names match the full English form
// used in films/*.yaml and labs/*.yaml's `country:` field (e.g. "United
// States", "South Korea", "Hong Kong"); a zone for a country nothing here
// covers yet just means detectUserLocation() finds no match, same as
// leaving the import checklist untouched.
const TZ_COUNTRY = {
    // Africa
    'Africa/Abidjan': 'Ivory Coast', 'Africa/Accra': 'Ghana', 'Africa/Addis_Ababa': 'Ethiopia',
    'Africa/Algiers': 'Algeria', 'Africa/Asmara': 'Eritrea', 'Africa/Bamako': 'Mali',
    'Africa/Bangui': 'Central African Republic', 'Africa/Banjul': 'Gambia', 'Africa/Bissau': 'Guinea-Bissau',
    'Africa/Blantyre': 'Malawi', 'Africa/Brazzaville': 'Republic of the Congo', 'Africa/Bujumbura': 'Burundi',
    'Africa/Cairo': 'Egypt', 'Africa/Casablanca': 'Morocco', 'Africa/Ceuta': 'Spain',
    'Africa/Conakry': 'Guinea', 'Africa/Dakar': 'Senegal', 'Africa/Dar_es_Salaam': 'Tanzania',
    'Africa/Djibouti': 'Djibouti', 'Africa/Douala': 'Cameroon', 'Africa/El_Aaiun': 'Western Sahara',
    'Africa/Freetown': 'Sierra Leone', 'Africa/Gaborone': 'Botswana', 'Africa/Harare': 'Zimbabwe',
    'Africa/Johannesburg': 'South Africa', 'Africa/Juba': 'South Sudan', 'Africa/Kampala': 'Uganda',
    'Africa/Khartoum': 'Sudan', 'Africa/Kigali': 'Rwanda', 'Africa/Kinshasa': 'Democratic Republic of the Congo',
    'Africa/Lagos': 'Nigeria', 'Africa/Libreville': 'Gabon', 'Africa/Lome': 'Togo',
    'Africa/Luanda': 'Angola', 'Africa/Lubumbashi': 'Democratic Republic of the Congo', 'Africa/Lusaka': 'Zambia',
    'Africa/Malabo': 'Equatorial Guinea', 'Africa/Maputo': 'Mozambique', 'Africa/Maseru': 'Lesotho',
    'Africa/Mbabane': 'Eswatini', 'Africa/Mogadishu': 'Somalia', 'Africa/Monrovia': 'Liberia',
    'Africa/Nairobi': 'Kenya', 'Africa/Ndjamena': 'Chad', 'Africa/Niamey': 'Niger',
    'Africa/Nouakchott': 'Mauritania', 'Africa/Ouagadougou': 'Burkina Faso', 'Africa/Porto-Novo': 'Benin',
    'Africa/Sao_Tome': 'Sao Tome and Principe', 'Africa/Tripoli': 'Libya', 'Africa/Tunis': 'Tunisia',
    'Africa/Windhoek': 'Namibia',
    // America
    'America/Adak': 'United States', 'America/Anchorage': 'United States', 'America/Anguilla': 'Anguilla',
    'America/Antigua': 'Antigua and Barbuda', 'America/Araguaina': 'Brazil', 'America/Argentina/Buenos_Aires': 'Argentina',
    'America/Aruba': 'Aruba', 'America/Asuncion': 'Paraguay', 'America/Bahia': 'Brazil',
    'America/Barbados': 'Barbados', 'America/Belem': 'Brazil', 'America/Belize': 'Belize',
    'America/Boa_Vista': 'Brazil', 'America/Bogota': 'Colombia', 'America/Boise': 'United States',
    'America/Cambridge_Bay': 'Canada', 'America/Campo_Grande': 'Brazil', 'America/Cancun': 'Mexico',
    'America/Caracas': 'Venezuela', 'America/Cayenne': 'French Guiana', 'America/Cayman': 'Cayman Islands',
    'America/Chicago': 'United States', 'America/Chihuahua': 'Mexico', 'America/Costa_Rica': 'Costa Rica',
    'America/Cuiaba': 'Brazil', 'America/Curacao': 'Curacao', 'America/Danmarkshavn': 'Greenland',
    'America/Dawson': 'Canada', 'America/Dawson_Creek': 'Canada', 'America/Denver': 'United States',
    'America/Detroit': 'United States', 'America/Dominica': 'Dominica', 'America/Edmonton': 'Canada',
    'America/Eirunepe': 'Brazil', 'America/El_Salvador': 'El Salvador', 'America/Fortaleza': 'Brazil',
    'America/Glace_Bay': 'Canada', 'America/Goose_Bay': 'Canada', 'America/Grand_Turk': 'Turks and Caicos Islands',
    'America/Grenada': 'Grenada', 'America/Guadeloupe': 'Guadeloupe', 'America/Guatemala': 'Guatemala',
    'America/Guayaquil': 'Ecuador', 'America/Guyana': 'Guyana', 'America/Halifax': 'Canada',
    'America/Havana': 'Cuba', 'America/Hermosillo': 'Mexico', 'America/Indiana/Indianapolis': 'United States',
    'America/Inuvik': 'Canada', 'America/Iqaluit': 'Canada', 'America/Jamaica': 'Jamaica',
    'America/Juneau': 'United States', 'America/Kralendijk': 'Bonaire', 'America/La_Paz': 'Bolivia',
    'America/Lima': 'Peru', 'America/Los_Angeles': 'United States', 'America/Managua': 'Nicaragua',
    'America/Manaus': 'Brazil', 'America/Marigot': 'Saint Martin', 'America/Martinique': 'Martinique',
    'America/Matamoros': 'Mexico', 'America/Mazatlan': 'Mexico', 'America/Menominee': 'United States',
    'America/Merida': 'Mexico', 'America/Mexico_City': 'Mexico', 'America/Miquelon': 'Saint Pierre and Miquelon',
    'America/Moncton': 'Canada', 'America/Monterrey': 'Mexico', 'America/Montevideo': 'Uruguay',
    'America/Montserrat': 'Montserrat', 'America/Nassau': 'Bahamas', 'America/New_York': 'United States',
    'America/Nome': 'United States', 'America/Noronha': 'Brazil', 'America/North_Dakota/Center': 'United States',
    'America/Nuuk': 'Greenland', 'America/Panama': 'Panama', 'America/Paramaribo': 'Suriname',
    'America/Phoenix': 'United States', 'America/Port-au-Prince': 'Haiti', 'America/Port_of_Spain': 'Trinidad and Tobago',
    'America/Porto_Velho': 'Brazil', 'America/Puerto_Rico': 'Puerto Rico', 'America/Punta_Arenas': 'Chile',
    'America/Rankin_Inlet': 'Canada', 'America/Recife': 'Brazil', 'America/Regina': 'Canada',
    'America/Resolute': 'Canada', 'America/Rio_Branco': 'Brazil', 'America/Santarem': 'Brazil',
    'America/Santiago': 'Chile', 'America/Santo_Domingo': 'Dominican Republic', 'America/Sao_Paulo': 'Brazil',
    'America/Scoresbysund': 'Greenland', 'America/Sitka': 'United States', 'America/St_Barthelemy': 'Saint Barthelemy',
    'America/St_Johns': 'Canada', 'America/St_Kitts': 'Saint Kitts and Nevis', 'America/St_Lucia': 'Saint Lucia',
    'America/St_Thomas': 'United States Virgin Islands', 'America/St_Vincent': 'Saint Vincent and the Grenadines',
    'America/Swift_Current': 'Canada', 'America/Tegucigalpa': 'Honduras', 'America/Thule': 'Greenland',
    'America/Tijuana': 'Mexico', 'America/Toronto': 'Canada', 'America/Tortola': 'British Virgin Islands',
    'America/Vancouver': 'Canada', 'America/Whitehorse': 'Canada', 'America/Winnipeg': 'Canada',
    'America/Yellowknife': 'Canada',
    // Antarctica / Arctic
    'Antarctica/Casey': 'Antarctica', 'Antarctica/Davis': 'Antarctica', 'Antarctica/Mawson': 'Antarctica',
    'Antarctica/McMurdo': 'Antarctica', 'Antarctica/Palmer': 'Antarctica', 'Antarctica/Troll': 'Antarctica',
    'Arctic/Longyearbyen': 'Norway',
    // Asia
    'Asia/Aden': 'Yemen', 'Asia/Almaty': 'Kazakhstan', 'Asia/Amman': 'Jordan',
    'Asia/Anadyr': 'Russia', 'Asia/Aqtau': 'Kazakhstan', 'Asia/Aqtobe': 'Kazakhstan',
    'Asia/Ashgabat': 'Turkmenistan', 'Asia/Atyrau': 'Kazakhstan', 'Asia/Baghdad': 'Iraq',
    'Asia/Bahrain': 'Bahrain', 'Asia/Baku': 'Azerbaijan', 'Asia/Bangkok': 'Thailand',
    'Asia/Barnaul': 'Russia', 'Asia/Beirut': 'Lebanon', 'Asia/Bishkek': 'Kyrgyzstan',
    'Asia/Brunei': 'Brunei', 'Asia/Chita': 'Russia', 'Asia/Colombo': 'Sri Lanka',
    'Asia/Damascus': 'Syria', 'Asia/Dhaka': 'Bangladesh', 'Asia/Dili': 'East Timor',
    'Asia/Dubai': 'United Arab Emirates', 'Asia/Dushanbe': 'Tajikistan', 'Asia/Famagusta': 'Cyprus',
    'Asia/Gaza': 'Palestine', 'Asia/Hebron': 'Palestine', 'Asia/Ho_Chi_Minh': 'Vietnam',
    'Asia/Hong_Kong': 'Hong Kong', 'Asia/Hovd': 'Mongolia', 'Asia/Irkutsk': 'Russia',
    'Asia/Jakarta': 'Indonesia', 'Asia/Jayapura': 'Indonesia', 'Asia/Jerusalem': 'Israel',
    'Asia/Kabul': 'Afghanistan', 'Asia/Kamchatka': 'Russia', 'Asia/Karachi': 'Pakistan',
    'Asia/Kathmandu': 'Nepal', 'Asia/Khandyga': 'Russia', 'Asia/Kolkata': 'India',
    'Asia/Krasnoyarsk': 'Russia', 'Asia/Kuala_Lumpur': 'Malaysia', 'Asia/Kuching': 'Malaysia',
    'Asia/Kuwait': 'Kuwait', 'Asia/Macau': 'Macau', 'Asia/Magadan': 'Russia',
    'Asia/Makassar': 'Indonesia', 'Asia/Manila': 'Philippines', 'Asia/Muscat': 'Oman',
    'Asia/Nicosia': 'Cyprus', 'Asia/Novokuznetsk': 'Russia', 'Asia/Novosibirsk': 'Russia',
    'Asia/Omsk': 'Russia', 'Asia/Oral': 'Kazakhstan', 'Asia/Phnom_Penh': 'Cambodia',
    'Asia/Pontianak': 'Indonesia', 'Asia/Pyongyang': 'North Korea', 'Asia/Qatar': 'Qatar',
    'Asia/Qostanay': 'Kazakhstan', 'Asia/Qyzylorda': 'Kazakhstan', 'Asia/Riyadh': 'Saudi Arabia',
    'Asia/Sakhalin': 'Russia', 'Asia/Samarkand': 'Uzbekistan', 'Asia/Seoul': 'South Korea',
    'Asia/Shanghai': 'China', 'Asia/Singapore': 'Singapore', 'Asia/Srednekolymsk': 'Russia',
    'Asia/Taipei': 'Taiwan', 'Asia/Tashkent': 'Uzbekistan', 'Asia/Tbilisi': 'Georgia',
    'Asia/Tehran': 'Iran', 'Asia/Thimphu': 'Bhutan', 'Asia/Tokyo': 'Japan',
    'Asia/Tomsk': 'Russia', 'Asia/Ulaanbaatar': 'Mongolia', 'Asia/Urumqi': 'China',
    'Asia/Ust-Nera': 'Russia', 'Asia/Vientiane': 'Laos', 'Asia/Vladivostok': 'Russia',
    'Asia/Yakutsk': 'Russia', 'Asia/Yangon': 'Myanmar', 'Asia/Yekaterinburg': 'Russia',
    'Asia/Yerevan': 'Armenia',
    // Atlantic
    'Atlantic/Azores': 'Portugal', 'Atlantic/Bermuda': 'Bermuda', 'Atlantic/Canary': 'Spain',
    'Atlantic/Cape_Verde': 'Cape Verde', 'Atlantic/Faroe': 'Faroe Islands', 'Atlantic/Madeira': 'Portugal',
    'Atlantic/Reykjavik': 'Iceland', 'Atlantic/South_Georgia': 'South Georgia and the South Sandwich Islands',
    'Atlantic/St_Helena': 'Saint Helena', 'Atlantic/Stanley': 'Falkland Islands',
    // Australia
    'Australia/Adelaide': 'Australia', 'Australia/Brisbane': 'Australia', 'Australia/Broken_Hill': 'Australia',
    'Australia/Darwin': 'Australia', 'Australia/Eucla': 'Australia', 'Australia/Hobart': 'Australia',
    'Australia/Lindeman': 'Australia', 'Australia/Lord_Howe': 'Australia', 'Australia/Melbourne': 'Australia',
    'Australia/Perth': 'Australia', 'Australia/Sydney': 'Australia',
    // Europe
    'Europe/Amsterdam': 'Netherlands', 'Europe/Andorra': 'Andorra', 'Europe/Astrakhan': 'Russia',
    'Europe/Athens': 'Greece', 'Europe/Belgrade': 'Serbia', 'Europe/Berlin': 'Germany',
    'Europe/Bratislava': 'Slovakia', 'Europe/Brussels': 'Belgium', 'Europe/Bucharest': 'Romania',
    'Europe/Budapest': 'Hungary', 'Europe/Busingen': 'Germany', 'Europe/Chisinau': 'Moldova',
    'Europe/Copenhagen': 'Denmark', 'Europe/Dublin': 'Ireland', 'Europe/Gibraltar': 'Gibraltar',
    'Europe/Guernsey': 'Guernsey', 'Europe/Helsinki': 'Finland', 'Europe/Isle_of_Man': 'Isle of Man',
    'Europe/Istanbul': 'Turkey', 'Europe/Jersey': 'Jersey', 'Europe/Kaliningrad': 'Russia',
    'Europe/Kirov': 'Russia', 'Europe/Kyiv': 'Ukraine', 'Europe/Lisbon': 'Portugal',
    'Europe/Ljubljana': 'Slovenia', 'Europe/London': 'United Kingdom', 'Europe/Luxembourg': 'Luxembourg',
    'Europe/Madrid': 'Spain', 'Europe/Malta': 'Malta', 'Europe/Mariehamn': 'Aland Islands',
    'Europe/Minsk': 'Belarus', 'Europe/Monaco': 'Monaco', 'Europe/Moscow': 'Russia',
    'Europe/Oslo': 'Norway', 'Europe/Paris': 'France', 'Europe/Podgorica': 'Montenegro',
    'Europe/Prague': 'Czech Republic', 'Europe/Riga': 'Latvia', 'Europe/Rome': 'Italy',
    'Europe/Samara': 'Russia', 'Europe/San_Marino': 'San Marino', 'Europe/Sarajevo': 'Bosnia and Herzegovina',
    'Europe/Saratov': 'Russia', 'Europe/Simferopol': 'Ukraine', 'Europe/Skopje': 'North Macedonia',
    'Europe/Sofia': 'Bulgaria', 'Europe/Stockholm': 'Sweden', 'Europe/Tallinn': 'Estonia',
    'Europe/Tirane': 'Albania', 'Europe/Ulyanovsk': 'Russia', 'Europe/Vaduz': 'Liechtenstein',
    'Europe/Vatican': 'Vatican City', 'Europe/Vienna': 'Austria', 'Europe/Vilnius': 'Lithuania',
    'Europe/Volgograd': 'Russia', 'Europe/Warsaw': 'Poland', 'Europe/Zagreb': 'Croatia',
    'Europe/Zurich': 'Switzerland',
    // Indian Ocean
    'Indian/Antananarivo': 'Madagascar', 'Indian/Chagos': 'British Indian Ocean Territory', 'Indian/Christmas': 'Australia',
    'Indian/Cocos': 'Australia', 'Indian/Comoro': 'Comoros', 'Indian/Kerguelen': 'French Southern Territories',
    'Indian/Mahe': 'Seychelles', 'Indian/Maldives': 'Maldives', 'Indian/Mauritius': 'Mauritius',
    'Indian/Mayotte': 'Mayotte', 'Indian/Reunion': 'Reunion',
    // Pacific
    'Pacific/Apia': 'Samoa', 'Pacific/Auckland': 'New Zealand', 'Pacific/Bougainville': 'Papua New Guinea',
    'Pacific/Chatham': 'New Zealand', 'Pacific/Chuuk': 'Micronesia', 'Pacific/Easter': 'Chile',
    'Pacific/Efate': 'Vanuatu', 'Pacific/Fakaofo': 'Tokelau', 'Pacific/Fiji': 'Fiji',
    'Pacific/Funafuti': 'Tuvalu', 'Pacific/Galapagos': 'Ecuador', 'Pacific/Gambier': 'French Polynesia',
    'Pacific/Guadalcanal': 'Solomon Islands', 'Pacific/Guam': 'Guam', 'Pacific/Honolulu': 'United States',
    'Pacific/Kanton': 'Kiribati', 'Pacific/Kiritimati': 'Kiribati', 'Pacific/Kosrae': 'Micronesia',
    'Pacific/Kwajalein': 'Marshall Islands', 'Pacific/Majuro': 'Marshall Islands', 'Pacific/Marquesas': 'French Polynesia',
    'Pacific/Midway': 'United States', 'Pacific/Nauru': 'Nauru', 'Pacific/Niue': 'Niue',
    'Pacific/Norfolk': 'Australia', 'Pacific/Noumea': 'New Caledonia', 'Pacific/Pago_Pago': 'American Samoa',
    'Pacific/Palau': 'Palau', 'Pacific/Pitcairn': 'Pitcairn Islands', 'Pacific/Pohnpei': 'Micronesia',
    'Pacific/Port_Moresby': 'Papua New Guinea', 'Pacific/Rarotonga': 'Cook Islands', 'Pacific/Saipan': 'Northern Mariana Islands',
    'Pacific/Tahiti': 'French Polynesia', 'Pacific/Tarawa': 'Kiribati', 'Pacific/Tongatapu': 'Tonga',
    'Pacific/Wake': 'United States', 'Pacific/Wallis': 'Wallis and Futuna',
};
